version: '3'

services:
  app:
    build: .
    image: ${DOCKER_REGISTRY:-}rails_app:latest
    entrypoint: ['bin/entry.sh']
    command: rails server -b 0.0.0.0
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: production
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 500M

  postgres:
    image: postgres:9.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 12345678

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    deploy:
      replicas: 1