version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
      - 35729:35729 # livereload port
    volumes:
      - './:/app'
      # - app-sync:/app:nocopy

  postgres:
    image: postgres:9.5
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: 12345678
